### ISSUE TITLE
needs to be updated to new API for Moodle 3.0

### ISSUE THREAD

**Issue by jderriks** [iandavidwild/moodle-mod_enhancedchoice#1]
Did work in Moodle 2.9, doesn't in 3.0.
Errors when only version.php is updated (change module-> into plugin->):

Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.
• line 717 of /course/moodleform_mod.php: call to debugging()
• line 47 of /mod/enhancedchoice/mod_form.php: call to moodleform_mod->add_intro_editor()
• line 196 of /lib/formslib.php: call to mod_enhancedchoice_mod_form->definition()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[0]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[1]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[2]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[3]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[4]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()

Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.
• line 717 of /course/moodleform_mod.php: call to debugging()
• line 47 of /mod/enhancedchoice/mod_form.php: call to moodleform_mod->add_intro_editor()
• line 196 of /lib/formslib.php: call to mod_enhancedchoice_mod_form->definition()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[0]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[1]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[2]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[3]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'limit[4]'? Defaulting to PARAM_RAW cleaning.
• line 1324 of /lib/formslib.php: call to debugging()
• line 296 of /lib/formslib.php: call to moodleform->detectMissingSetType()
• line 207 of /lib/formslib.php: call to moodleform->_process_submission()
• line 86 of /course/moodleform_mod.php: call to moodleform->__construct()
• line 254 of /course/modedit.php: call to moodleform_mod->__construct()

add_to_log() has been deprecated, please rewrite your code to the new events API
• line 50 of /lib/deprecatedlib.php: call to debugging()
• line 79 of /mod/enhancedchoice/view.php: call to add_to_log()

**Comment by iandavidwild** [comment]
Hi Jan,

I have created a new MOODLE_31 branch and updated the code accordingly. I will mark this issue as closed but, in the meantime, if you experience any other problems then please do feel free to open another issue.

Kind regards,

Ian.
